CREATE DATABASE  ECOMMERCEDB;
USE ECOMMERCEDB;

CREATE TABLE CUSTOMERS(
CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) UNIQUE,
PHONE VARCHAR(15),
JOIN_DATE DATE 
);
CREATE TABLE CATEGORIES(
CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
CATEGORY_NAME VARCHAR(50) NOT NULL
);
CREATE TABLE PRODUCTS (
PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
PRODUCT_NAME VARCHAR(100) NOT NULL,
CATEGORY_ID INT,
PRICE DECIMAL(10,2),
STOCK_QUANTITY INT,
FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE TABLE ORDERS (
ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
CUSTOMER_ID INT,
ORDER_DATE DATE,
TOTAL_AMOUNT DECIMAL(10,2),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE ORDER_DETAILS (
ORDER_DETAIL_ID INT AUTO_INCREMENT PRIMARY KEY,
ORDER_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
PRICE DECIMAL(10,2),
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

INSERT INTO CUSTOMERS (name, email, phone, join_date)
Values
('Harnika Reddy', 'posimreddyharnika@gmil.com', '88857700488', '2025-01-05'),
('Vani', 'vani@gmail.com', '9876543210', '2025-02-05'),
('Sneha Singh', 'sneha@gmail.com', '9123456789', '2025-03-15');

INSERT INTO CATEGORIES (CATEGORY_NAME)
VALUES
('ELECTRONICS'),
('CLOTHING'),
('BOOKS');

INSERT INTO PRODUCTS(PRODUCT_NAME, CATEGORY_ID, PRICE, STOCK_QUANTITY)
VALUES
('SMARTPHONE', 1,20000, 50),
('LAPTOP', 1, 55000,30),
('T-SHIRT', 2, 500, 100),
('Jeans', 2, 1200, 80), 
('Novel', 3, 300,60);
SELECT * FROM PRODUCTS;

INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT)
VALUES
(1,'2025-11-01',20500),
(2, '2025-11-02', 1250),
(3, '2025-11-03', 300);

INSERT INTO ORDER_DETAILS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE)
VALUES
(1,1,1,20000),
(1,5,1,500),
(2,3,2,500),
(2,4,1,250),
(3,5,1,300);

SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE FROM ORDERS;

SELECT P.PRODUCT_NAME,SUM(OD.QUANTITY) AS TOTAL_SOLD
FROM ORDER_DETAILS OD
JOIN PRODUCTS p ON OD.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SOLD DESC;

SELECT C.CATEGORY_NAME, SUM(OD.QUANTITY * OD.PRICE) AS CATEGORY_REVENUE
FROM ORDER_DETAILS OD
JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
JOIN CATEGORIES C ON P.CATEGORY_ID = C.CATEGORY_ID
GROUP BY C.CATEGORY_ID;

SELECT CU.NAME, O.ORDER_DATE, P.PRODUCT_NAME, OD.QUANTITY, OD.PRICE
FROM ORDERS O
JOIN CUSTOMERS CU ON O.CUSTOMER_ID = CU.CUSTOMER_ID
JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
WHERE CU.name = 'Harnika Reddy';

SELECT PRODUCT_NAME,STOCK_QUANTITY
FROM PRODUCTS
WHERE STOCK_QUANTITY < 50;

SELECT MONTH(ORDER_DATE) AS MONTH, SUM(TOTAL_AMOUNT) AS REVENUE
FROM ORDERS
GROUP BY MONTH(ORDER_DATE)
ORDER BY MONTH;
